[package]
name = "xdp-starter-userspace"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "xdp-starter-userspace-component"
path = "src/main.rs"

[build-dependencies]
anyhow = { workspace = true }
aya-build = { workspace = true }

[dependencies]
